version: "3.9"
services:
  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - JWT_SECRET=your-secret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
